export const USER_POSTS_FETCH_REQUESTED = 'USER_POSTS_FETCH_REQUESTED';
export const USER_POSTS_FETCH_SUCESSDED = 'USER_POSTS_FETCH_SUCESSDED';
export const USER_POSTS_FETCH_FAILED = 'USER_POSTS_FETCH_FAILED';